# Generated by Django 6.0.1 on 2026-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_temporary_host_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
