# Generated by Django 6.0 on 2026-01-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
                ('is_live', models.BooleanField(default=False)),
                ('starting_soon', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('button_text', models.CharField(default='View Tournament', max_length=50)),
                ('button_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
