# Generated by Django 6.0.1 on 2026-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslide',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
