# Generated by Django 6.0.1 on 2026-02-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eventslide_button_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSlide',
        ),
    ]
