# Generated by Django 6.0.1 on 2026-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_is_approved_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_category',
            field=models.CharField(choices=[('fps', 'First Person Shooter'), ('action', 'Action'), ('adventure', 'Adventure'), ('strategy', 'Strategy'), ('card', 'Card Games')], default='action', max_length=20),
        ),
    ]
