# Generated by Django 6.0.1 on 2026-02-08 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='button_text',
            field=models.CharField(default='View Tournament', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default='hero/default.jpg', upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournament',
            name='starting_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
